import 'package:advance_flutter_app/modal/countrydetailmodal/countrydetailmodal.dart';
import 'package:advance_flutter_app/modal/covidmodal.dart';
import 'package:flutter/material.dart';
import 'package:advance_flutter_app/helper/covidhelper.dart';

class CovidProvider with ChangeNotifier {
  List<CovidDataModel> covidData = [];


  List<Autogenerated> covidDetailData = [];



  Future<void> covidDataGet() async {
    CovidHelper helper = CovidHelper();
    final response = await helper.covidAPI();

    if (response != null) {
      covidData = (response as List)
          .map((item) => CovidDataModel.fromMap(item))
          .toList();
       notifyListeners();
    } else {
      print('Error');
    }
  }

  Future<void> covidDetailDataGet() async {

    CovidHelper helper = CovidHelper();
    final response = await helper.covidDetailAPI();

    if (response != null) {
       List<dynamic> responseData = response as List;

       covidDetailData = (response as List)
           .map((item) => Autogenerated.fromJson(item)).cast<Autogenerated>()
           .toList();
       notifyListeners();
    } else {
      print('Error');
    }
  }

}