import 'package:advance_flutter_app/modal/countrydetailmodal/countrydetailmodal.dart';
import 'package:advance_flutter_app/modal/covidmodal.dart';
import 'package:flutter/material.dart';
import 'package:advance_flutter_app/helper/covidhelper.dart';

class CovidProvider with ChangeNotifier {
  List<CovidDataModel> covidData = [];


  List<Autogenerated> covidDetailData = [];



  Future<void> covidDataGet() async {
    CovidHelper helper = CovidHelper();
    final response = await helper.covidAPI();

    if (response != null) {
      covidData = (response as List)
          .map((item) => CovidDataModel.fromMap(item))
          .toList();
       notifyListeners();
    } else {
      print('Error');
    }
  }

  Future<void> covidDetailDataGet() async {

    CovidHelper helper = CovidHelper();
    final response = await helper.covidDetailAPI();

    if (response != null) {
       List<dynamic> responseData = response as List;

       covidDetailData = responseData
          .map((item) => Autogenerated.fromJson(item))
          .toList();

      Autogenerated newAutogenerated = Autogenerated(data: [
        Data(
            date: "2024-12-17",
            confirmed: 50000,
            deaths: 1000,
            recovered: 40000,
            confirmedDiff: 500,
            deathsDiff: 10,
            recoveredDiff: 400,
            lastUpdate: "2024-12-17T00:00:00Z",
            active: 10000,
            activeDiff: 200,
            fatalityRate: 2.0,
            region: Region(name: "China", iso: "CN", province: "Beijing", lat: "39.9042", long: "116.4074")
        )
      ]);

      covidDetailData.add(newAutogenerated);

      print(covidDetailData);
      notifyListeners();
    } else {
      print('Error');
    }
  }

}